version: '3'

services:
  database:
    image: mysql:8
    tty: true
    ports:
      - '4206:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_app
    volumes:
      - database:/var/lib/mysql
    networks:
      - mariadb
  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=my_app
    volumes:
      - ./:/app
    depends_on:
      - database
    networks:
      - mariadb
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - database
    networks:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - phpmyadmin:/var/www/html/phpmyadmin
volumes:
  database:
  phpmyadmin:
  app:
networks:
  mariadb:
    driver: bridge


